CREATE DATABASE IF NOT EXISTS todo;
USE todo;
CREATE TABLE IF NOT EXISTS `tasks`(
    `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `creation_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `last_update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `description` VARCHAR(5000),
    `status` BOOLEAN NOT NULL DEFAULT FALSE
);
